version: '3'
services:
  flyway:
    image: flyway/flyway:8
    command: migrate
    volumes:
      - ./sql/migrations:/flyway/sql
      - ./sql:/flyway/conf
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:14
    restart: always
    env_file:
      ./sql/db.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 10

  redis_cache:
    image: redis:6
    restart: always
    ports:
      - 6379:6379

  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis_cache
      - database
      - flyway
