name: Deploy database changes

on:
  workflow_dispatch:

jobs:
  flyway-deploy:
    name: Deploy
    runs-on: database
    environment: Test
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Run migrate
      run: docker-compose run flyway
    - name: Print the flyway logs, if needed later
      run: docker compose logs flyway
      if: always()
